### ISSUE TITLE
Ignore `createdby` for duplicate check

### ISSUE THREAD

**Issue by Barakur** [georgringer/redirect_generator#16]
The duplicate check for redirects also checks for `createdby` in `RedirectRepository`:

```
$queryBuilder->expr()->eq('createdby', $queryBuilder->createNamedParameter(self::CUSTOM_USER_ID, \PDO::PARAM_INT)),
```

Who created the redirect is not relevant for the duplicate check. This is actually a bug. If a user manually creates a redirect and the same redirect should be imported it will be added as a duplicate.

**Comment by georgringer** [comment]
wanna do a PR?

**Comment by Barakur** [comment]
Yes, I will provide a PR soon.
