### ISSUE TITLE
[Feature] E-Mail Notification for Warnings / Errors (support periodic automatic imports)

### ISSUE THREAD

**Issue by Barakur** [georgringer/redirect_generator#19]
So far this extension isn't really suited for periodic automatic imports (which is a use case I require). To fully support such a use case  the folllowing features are required imho:

1. Optional E-Mail notification on warnings / errors
2. Different return codes based on errors / warnings with adjusted console output to make the importer less verbose (if so desired)
3. Make the commands schedulable with configurations in the scheduler task for import files etc.

I see 1) as mandatory since 2) and 3) can be achieved with a cron job that redirects output to `dev/null` in the worst case.

I could provide PRs for the feature if that is ok.

**Comment by georgringer** [comment]
thanks for your ideas. yes looks good, please go ahead. maybe split it into different PR and just ping me via slack if you got any questions!
