### ISSUE TITLE
PHP 7.2 support

### ISSUE THREAD

**Issue by ayacoo** [georgringer/redirect_generator#3]
Hi Georg,

I could not find anything about PHP support. Therefore first an issue. (PR can follow if you want.)

CLI call with PHP 7.2.x
`Uncaught TYPO3 Exception syntax error, unexpected ')'
thrown in file ...public\typo3conf\ext\redirect_generator\Classes\Repository\RedirectRepository.php
in line 32
`

The trigger is the trailing comma. Since you also support PHP 7.2, would that make sense to correct?

**Comment by georgringer** [comment]
Yes pls pr
