### ISSUE TITLE
Support for external URL

### ISSUE THREAD

**Issue by ayacoo** [georgringer/redirect_generator#4]
Currently, external URLs are not supported. What do you think of an option --type, which u.a. external URLs supported?

I have the same problem with pages that have route enhancers. I would normally have to save this as an external URL. One would have to dissolve the parameters and recognize. But does not seem so trivial to me for a first solution ;-)

**Comment by georgringer** [comment]
what do you mean with support for external urls. can you give an example?

**Comment by ayacoo** [comment]
In my first example, formerly existing websites (source) should be redirected to a target from the company group. This domain is not managed in TYPO3. In your extension, there is a check on "site"  (configurations) within the TYPO3 system.

Second example are route enhancer. Maybe I have misconfigured here too. Example: I redirect an old source to the new target http://www.example.com/listview/slug Listview is a page in TYPO3 and slug is a route enhancer, 

EXT:redirect_generator finds "listview" and set t3://page:1 But it should be a page with arguments or simple an external url. The first case would be preferable, but I think it's a tough one. Would be a workaround with this new type.

Hopefully it is clearer now?

**Comment by ayacoo** [comment]
Another addendum:
Of course I tried to use the external-domain option. If I set the option, it works to redirect the news because it is recognized as an external URL. But this means that I lose the reference to the ID on the normal pages.

I hope that makes my example clearer.

**Comment by georgringer** [comment]
is this solved with the merging the PR?

**Comment by ayacoo** [comment]
Yes ;-)
